Add docsify-live-demo plugin
docsifyjs/awesome-docsify pull request #243
Opened 2023-01-29 19:16 UTC by kossidts

I have add a the live demo plugin to the list of plugins

2023-01-29 23:59 UTC, Koooooo-7 requested changes
Hi @kossidts , plz remove the format stuff and fix the ci.

2023-01-30 06:28 UTC, kossidts commented
Thanks @Koooooo-7, should be fixed now. 
I have tested the linting, there are now two remaining error in my feature branch as well as in the master, which I didn't touch. So I guess it's okay - or can I take any further action to resolve them?

```sh
 README.md:1:1
  ✖  1:1  The repository should have "awesome" as a GitHub topic       remark-lint:awesome-github
  ✖  1:1  The repository should have "awesome-list" as a GitHub topic  remark-lint:awesome-github
 2 errors
```

2023-01-30 06:36 UTC, Koooooo-7 commented
> Thanks @Koooooo-7, should be fixed now. I have tested the linting, there are now two remaining error in my feature branch as well as in the master, which I didn't touch. So I guess it's okay - or can I take any further action to resolve them?
> 
> ```shell
>  README.md:1:1
>   ✖  1:1  The repository should have "awesome" as a GitHub topic       remark-lint:awesome-github
>   ✖  1:1  The repository should have "awesome-list" as a GitHub topic  remark-lint:awesome-github
>  2 errors
> ```

It looks fine here. thx for ur contribution.👌

2023-01-30 06:36 UTC, Koooooo-7 approved these changes

2023-02-03 05:33 UTC, merged